// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BlueSteel
{
    internal sealed partial class Vsix
    {
        public const string Id = "BlueSteel.e1e706e2-05d3-4da9-8754-652cd8ab65f4";
        public const string Name = "Blue Steel Theme";
        public const string Description = @"A theme pack for Visual Studio 2026 containing several light, dark, and solarized color themes";
        public const string Language = "en-US";
        public const string Version = "1.0.900";
        public const string Author = "Mads Kristensen";
        public const string Tags = "theme, solarized, light, dark";
        public const bool IsPreview = false;
    }
}
